### ISSUE TITLE
Driver Update

### ISSUE THREAD

**Issue by moriel5** [kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers#1]
Hi, there is a newer driver package version, labeled PG465, and it also supports 32-bit (for those who use it).
This is taken from the Dell Vostro 3568 drivers (the driver version here is 6.0.1.8403).

By the way, do you think that it is would be possible to enable seperate outputs for internal and external speakers (and to possibly allow simultaneus output)?

**Comment by kevinshroff** [comment]
> Hi, there is a newer driver package version, labeled PG465, and it also supports 32-bit (for those who use it). This is taken from the Dell Vostro 3568 drivers (the driver version here is 6.0.1.8403).

32Bit is not supported right now - not due to lack of driver support but personal choice, as it requires redoing the mods for every hardware ID in WIN32, which is already quite time consuming for WIN64 with which I am not done with yet. Once I've completed support for all supported Realtek hardware for WIN64, I will consider adding support for 32bit devices.

> By the way, do you think that it is would be possible to enable seperate outputs for internal and external speakers (and to possibly allow simultaneus output)?

It should be possible, considering @syscl wrote software for macOS XPS 13 hackintoshes which allows to configure audio input/output under macOS like with stock Dell drivers, however this is probably a considerable undertaking of which I or others currently have no plans to pursue.
