### ISSUE TITLE
Prepare for future development

### ISSUE THREAD

**Issue by Esgariot** [kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers#15]
Could you try to write down what you did and how you did it so that when you might someday ultimately decide to abandon this project someone else can pick up where you left off?
 Looking at commit history the changes feel like black magic and I'm sure lot of research was put into getting this project where it's at.

**Comment by moriel5** [comment]
There is no "black magic" here, and while I do not understand most of the commits either, I do have a slight idea what is being changed, so I can safely say that if someone decides to fork these drivers, they will understand the commits without much difficulty (and they can always ask), otherwise they will have to learn how drivers work (on the technical level), since that is a necessity for modding drivers.
